// CLINT_rtc.cc - host Vseq (rt_dev original form)
// Host no-op under PRELOAD. Self-checking type, the "weakest" example of the co-sim frame.
// (representative co-sim example is PLIC_enable.cc - uses trigger_irq+host_*bp -> works after stage 3)
//
// Position in the frame: functions of this Vseq are dispatched from verif_tsi_t(host)
// calling master_*/host_*bp. But CLINT/rtc does nothing under PRELOAD.

#include "S5740_mcu_tests.h"   // generated by import_test.py (dispatcher) - replaced by the frame on chipyard
#include "CLINT_rtc.h"

bool CLINT_rtc()
{
#ifndef PRELOAD
    host_set_bp(BP_MEM_WRITE);
#endif
    return true;
}

bool CLINT_rtc_check()
{
    return true;
}
